packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - sharp

catalog:
  # Core dependencies
  typescript: 5.9.3
  uuid: 13.0.0

  # Testing
  vitest: 4.0.6
  '@vitest/coverage-v8': 4.0.6
  vite-tsconfig-paths: 5.1.4

  # Linting
  '@biomejs/biome': 2.3.7

  # Astro (UI-specific but version managed centrally)
  astro: 5.15.8
  '@astrojs/check': 0.9.5
  '@astrojs/solid-js': 5.1.3
  'solid-js': 1.9.10
